apiVersion: apps/v1
kind: Deployment
metadata:
  name: adalalegalis-postgres
  labels:
    app: adalalegalis-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adalalegalis-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adalalegalis-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: adalalegalis-db-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: adalalegalis-db-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: "adalalegalis"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: adalalegalis-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: Secret
metadata:
  name: adalalegalis-db-secrets
type: Opaque
data:
  # These are placeholder values that will be replaced by actual secrets in the CI/CD pipeline
  postgres-user: cG9zdGdyZXM=
  postgres-password: cG9zdGdyZXNwYXNzd29yZA==
